import { Genre } from '@prisma/client';

export const tracks = [
  {
    name: 'Acoustic Breeze',
    src: 'https://dl.dropboxusercontent.com/s/8lpv3kkiiyd96v5/bensound-acousticbreeze.mp3?dl=0',
    artist: 'Benjamin_Tissot',
    duration: 157,
    genre: Genre.Acoustic,
    image: '/cover.jpg',
  },
  {
    name: 'Sunny',
    src: 'https://dl.dropboxusercontent.com/s/igu967tw6slfchq/bensound-sunny.mp3?dl=0',
    artist: 'Benjamin_Tissot',
    duration: 140,
    genre: Genre.Acoustic,
    image: '/cover.jpg',
  },
  {
    name: 'Small Guitar',
    src: 'https://dl.dropboxusercontent.com/s/ivxmno3dw08rgso/bensound-smallguitar.mp3?dl=0',
    artist: 'Benjamin_Tissot',
    duration: 202,
    genre: Genre.Acoustic,
    image: '/cover.jpg',
  },
  {
    name: 'The Lounge',
    src: 'https://dl.dropboxusercontent.com/s/odo51gkipvavb9a/bensound-thelounge.mp3?dl=0',
    artist: 'Benjamin_Tissot',
    duration: 256,
    genre: Genre.Jazz,
    image: '/cover.jpg',
  },
  {
    name: 'The Jazz Piano',
    src: 'https://dl.dropboxusercontent.com/s/rx2nqsna9tic9wp/bensound-thejazzpiano.mp3?dl=0',
    artist: 'Benjamin_Tissot',
    duration: 160,
    genre: Genre.Jazz,
    image: '/cover.jpg',
  },
  {
    name: 'Romantic',
    src: 'https://dl.dropboxusercontent.com/s/y3y8dvn0vxuf63b/bensound-romantic.mp3?dl=0',
    artist: 'Benjamin_Tissot',
    duration: 236,
    genre: Genre.Jazz,
    image: '/cover.jpg',
  },
  {
    name: 'All That',
    src: 'https://dl.dropboxusercontent.com/s/1s2o8xmgo85xapb/bensound-allthat.mp3?dl=0',
    artist: 'Benjamin_Tissot',
    duration: 236,
    genre: Genre.Jazz,
    image: '/cover.jpg',
  },
  {
    name: 'Moose',
    src: 'https://dl.dropboxusercontent.com/s/usuyqbejfaa50x1/bensound-moose.mp3?dl=0',
    artist: 'Benjamin_Tissot',
    duration: 160,
    genre: Genre.Electronica,
    image: '/cover.jpg',
  },
  {
    name: 'House',
    src: 'https://dl.dropboxusercontent.com/s/3u6vpjry1ouq0pu/bensound-house.mp3?dl=0',
    artist: 'Benjamin_Tissot',
    duration: 259,
    genre: Genre.Electronica,
    image: '/cover.jpg',
  },
  {
    name: 'Endless Motion',
    src: 'https://dl.dropboxusercontent.com/s/jpjoejz0t3hpsag/bensound-endlessmotion.mp3?dl=0',
    artist: 'Benjamin_Tissot',
    duration: 180,
    genre: Genre.Electronica,
    image: '/cover.jpg',
  },
  {
    name: 'Rumble',
    src: 'https://dl.dropboxusercontent.com/s/ge186gmpyquus2f/bensound-rumble.mp3?dl=0',
    artist: 'Benjamin_Tissot',
    duration: 154,
    genre: Genre.Rock,
    image: '/cover.jpg',
  },
  {
    name: 'High Octane',
    src: 'https://dl.dropboxusercontent.com/s/uer6wpzjxh6vvpi/bensound-highoctane.mp3?dl=0',
    artist: 'Benjamin_Tissot',
    duration: 154,
    genre: Genre.Rock,
    image: '/cover.jpg',
  },
  {
    name: 'Going Higher',
    src: 'https://dl.dropboxusercontent.com/s/mkn91yrzlwx5uuw/bensound-goinghigher.mp3?dl=0',
    artist: 'Benjamin_Tissot',
    duration: 244,
    genre: Genre.Rock,
    image: '/cover.jpg',
  },
  {
    name: 'Beyond The Line',
    src: 'https://dl.dropboxusercontent.com/s/pnlgzj3outpq1ag/bensound-beyondtheline.mp3?dl=0',
    artist: 'Benjamin_Tissot',
    duration: 186,
    genre: Genre.Rock,
    image: '/cover.jpg',
  },
  {
    name: 'The Elevator Bossa Nova',
    src: 'https://dl.dropboxusercontent.com/s/wfz2zkaf3a3ynak/theelevatorbossanova.mp3?dl=0',
    artist: 'Benjamin_Tissot',
    duration: 123,
    genre: Genre.Jazz,
    image: '/cover.jpg',
  },
];
